// ─── Product ────────────────────────────────────────────────────────────────

export interface Product {
    // MongoDB returns _id; the backend may also expose id via virtuals
    _id?: string;
    id: string;
    name: string;
    price: number;
    category: string;
    createdAt?: string; // auto-generated by Mongoose timestamps — may be absent in raw import
    updatedAt?: string;

    // Full backend fields (product.model.js)
    description?: string;
    image?: string;        // backend field name is 'image', not 'imageUrl'
    stock?: number;        // aligned with backend 'stock' field
}

// ─── Cart ───────────────────────────────────────────────────────────────────

export interface CartItem {
    product: Product;
    quantity: number;
}


// ─── Orders ─────────────────────────────────────────────────────────────────

export interface OrderItem {
    product: string | Product;
    productName: string;
    priceAtPurchase: number;
    quantity: number;
}

export type OrderStatus = 'Pending' | 'Completed' | 'Cancelled';

export interface Order {
    _id: string;
    id?: string;
    user: string | User;
    items: OrderItem[];
    totalAmount: number;
    status: OrderStatus;
    createdAt: string;
    updatedAt: string;
}


// ─── User ───────────────────────────────────────────────────────────────────

// Matches the backend enum exactly: role: { enum: ['Admin', 'client'] }
export type UserRole = 'Admin' | 'client';

export interface User {
    _id?: string;
    id: string;
    nom: string;      // Last name
    prenom: string;   // First name
    email: string;
    role: UserRole;
    age?: number;
    telephone?: string;
    adresse?: {
        rue?: string;
        ville?: string;
        codePostal?: string;
        pays?: string;
    };
    actif?: boolean;
    profilePicture?: string;
    createdAt?: string;
    updatedAt?: string;
}

// ─── Auth ───────────────────────────────────────────────────────────────────

export interface AuthResponse {
    token: string;
    user: User;
}

export interface LoginCredentials {
    email: string;
    password: string;
}

// ─── API Response Wrappers ──────────────────────────────────────────────────

export interface ApiResponse<T> {
    success: boolean;
    data: T;
    message?: string;
}

export interface PaginatedResponse<T> {
    data: T[];
    total: number;
    page: number;
    limit: number;
}

export type CartResponse = CartItem[];

